# Generated by Django 5.2.3 on 2025-07-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_masters_managers_alter_masters_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='username',
        ),
    ]
