# Generated by Django 5.2.3 on 2025-06-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_echeance', models.DateTimeField()),
                ('priorite', models.CharField(choices=[('faible', 'low'), ('moyenne', 'medium'), ('haute', 'high')], default='faible')),
                ('status', models.CharField(choices=[('à faire', 'to do'), ('en cours', 'in progress'), ('terminé', 'finished')], default='à faire')),
            ],
        ),
    ]
