# Generated by Django 5.2.3 on 2025-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
