# Generated by Django 5.2.3 on 2025-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('à faire', 'todo'), ('en cours', 'in progress'), ('terminé', 'finished')], default='à faire'),
        ),
    ]
